### ISSUE TITLE
Enxyme Test (Mocha): Cannot read property '_resolvedStyles' of undefined

### ISSUE THREAD

**Issue by joncursi** [rofrischmann/react-look#282]
I have a React component that renders completely normal in the browser:

```jsx
import React, { Component, PropTypes } from 'react';
...
import look, { StyleSheet } from 'react-look';

const styles = StyleSheet.create({
  drawer__link: {
    textDecoration: 'none',
  },
  'drawer__link--active': {
    backgroundColor: 'rgba(0, 0, 0, .03)',
  },
});

class LeftDrawer extends Component {

  ...
  render() {
    return (
      <div>Activity</div>
    );
  }
}

...
export default look(LeftDrawer);
```

But fails when being tested through enzyme (using mocha):

```
import React from 'react';
import { describe, it } from 'mocha';
import { expect } from 'chai';
import { shallow } from 'enzyme';

import LeftDrawer from '../../imports/ui/components/LeftDrawer/LeftDrawer.jsx';

describe('<LeftDrawer />', () => {
  it('contains spec with an expectation', () => {
    expect(shallow(<LeftDrawer />).contains('Activity')).to.equal(true);
  });
});

```

Error log:

```
  0 passing (62ms)
  1 failing

  1) <LeftDrawer /> contains spec with an expectation:
     TypeError: Cannot read property '_resolveStyles' of undefined
      at LookComponent.render (node_modules/react-look-core/lib/core/enhancer.js:91:40)
      at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (node_modules/react/lib/ReactCompositeComponent.js:687:34)
      at [object Object].ReactCompositeComponentMixin.performInitialMount (node_modules/react/lib/ReactCompositeComponent.js:291:30)
      at [object Object].ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:222:21)
      at [object Object].wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
      at [object Object].ReactShallowRenderer._render (node_modules/react/lib/ReactTestUtils.js:385:14)
      at _batchedRender (node_modules/react/lib/ReactTestUtils.js:366:12)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
      at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:97:20)
      at [object Object].ReactShallowRenderer.render (node_modules/react/lib/ReactTestUtils.js:359:16)
      at [object Object].render (node_modules/enzyme/build/react-compat.js:146:39)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:81:21)
      at shallow (node_modules/enzyme/build/shallow.js:21:10)
      at Context.<anonymous> (AppLayout-test.js:10:12)
```

The test succeeds if I strip out react-look from the JSX component:

```
import React, { Component, PropTypes } from 'react';
class LeftDrawer extends Component {

  render() {
    return (
      <div>Activity</div>
    );
  }
}

export default LeftDrawer;
```

Thoughts?

**Comment by rofrischmann** [comment]
Look requires the `<LookRoot>` Component wrapping all other to apply the CSS styles to the DOM and to pass the config via context. 
You could just use `<LookRoot config={..}><LeftDrawer/></LookRoot>` for your tests.
Another option is to use the [react-look-test-utils](https://github.com/rofrischmann/react-look/tree/develop/packages/react-look-test-utils#getresolvedstyleelement-component-config--pseudoclass-mediaconfig), but I am honest, I never really had time to fully test them. Still they're working fine for me. (Note: the global instance is very useful this way)

**Comment by rofrischmann** [comment]
I will also close this one. As you did not comment any further I guess the solution helped to clear the case.
